global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'distributed-cache'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'dcache-node-1:8000'
          - 'dcache-node-2:8000'
          - 'dcache-node-3:8000'
        labels:
          service: 'dcache'
